# This config file is the one that @wez uses on a PixelBook Go

device_name = "AT Translated Set 2 keyboard"

# Hold capslock for Fn, tap for esc
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_FN"]
tap = [] #TODO: ["KEY_ESC"]

# Swap left Alt with Super
[[remap]]
input = ["KEY_LEFTALT"]
output = ["KEY_LEFTMETA"]

# Swap left Super with Alt
[[remap]]
input = ["KEY_LEFTMETA"]
output = ["KEY_LEFTALT"]

# Fn+H = Left
[[remap]]
input = ["KEY_FN", "KEY_H"]
output = ["KEY_LEFT"]

# Fn+J = Down
[[remap]]
input = ["KEY_FN", "KEY_J"]
output = ["KEY_DOWN"]

# Fn+K = Up
[[remap]]
input = ["KEY_FN", "KEY_K"]
output = ["KEY_UP"]

# Fn+L = Right
[[remap]]
input = ["KEY_FN", "KEY_L"]
output = ["KEY_RIGHT"]

# Fn+U = Page Up
[[remap]]
input = ["KEY_FN", "KEY_U"]
output = ["KEY_PAGEUP"]

# Fn+I = Home
[[remap]]
input = ["KEY_FN", "KEY_I"]
output = ["KEY_HOME"]

# Fn+O = Page Down
[[remap]]
input = ["KEY_FN", "KEY_O"]
output = ["KEY_PAGEDOWN"]

# Fn+N = End
[[remap]]
input = ["KEY_FN", "KEY_N"]
output = ["KEY_END"]
